SELECT
    FOOD_PRODUCT.PRODUCT_ID 'PRODUCT_ID',
    FOOD_PRODUCT.PRODUCT_NAME 'PRODUCT_NAME',
    SUM(FOOD_PRODUCT.PRICE * FOOD_ORDER.AMOUNT) 'TOTAL_SALES'
FROM
    FOOD_ORDER
LEFT JOIN
    FOOD_PRODUCT
    ON FOOD_ORDER.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
WHERE
    DATE_FORMAT(PRODUCE_DATE, '%Y%m') = '202205'
GROUP BY
    FOOD_PRODUCT.PRODUCT_ID
ORDER BY
    SUM(FOOD_PRODUCT.PRICE * FOOD_ORDER.AMOUNT) DESC,
    FOOD_PRODUCT.PRODUCT_ID